export const restaurants = [
    {
        id: 1,
        name: 'Italian Delight',
        rating: 4,
        distance: '2 km',
        imageUri: 'https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?cs=srgb&dl=pexels-pixabay-262978.jpg&fm=jpg',
        cuisine: 'Italian',
        openingHours: '10:00 AM - 10:00 PM',
        description: 'Authentic Italian cuisine with a wide variety of pasta and pizza.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
    {
        id: 2,
        name: 'Sushi Haven',
        rating: 3,
        distance: '3 km',
        imageUri: 'https://images.pexels.com/photos/262978/pexels-photo-262978.jpeg?cs=srgb&dl=pexels-pixabay-262978.jpg&fm=jpg',
        cuisine: 'Japanese',
        openingHours: '11:30 AM - 9:00 PM',
        description: 'Fresh and delicious sushi served in a cozy atmosphere.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
    {
        id: 3,
        name: 'Burger Palace',
        rating: 4,
        distance: '1.5 km',
        imageUri: 'https://images.pexels.com/photos/70497/pexels-photo-70497.jpeg?cs=srgb&dl=pexels-pixabay-70497.jpg&fm=jpg',
        cuisine: 'American',
        openingHours: '11:00 AM - 10:30 PM',
        description: 'Mouthwatering burgers and fries made with the finest ingredients.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
    {
        id: 4,
        name: 'Mexican Fiesta',
        rating: 5,
        distance: '5 km',
        imageUri: 'https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?cs=srgb&dl=pexels-pixabay-461198.jpg&fm=jpg',
        cuisine: 'Mexican',
        openingHours: '12:00 PM - 11:00 PM',
        description: 'Spicy and flavorful Mexican dishes that will transport you to Mexico.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
    {
        id: 5,
        name: 'Noodle House',
        rating: 4,
        distance: '4 km',
        imageUri: 'https://images.pexels.com/photos/731923/pexels-photo-731923.jpeg?cs=srgb&dl=pexels-kaboompics-com-731923.jpg&fm=jpg',
        cuisine: 'Asian',
        openingHours: '12:30 PM - 10:00 PM',
        description: 'Delicious noodle dishes from various Asian cuisines.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
    {
        id: 6,
        name: 'Steakhouse Grill',
        rating: 3,
        distance: '3.5 km',
        imageUri: 'https://images.pexels.com/photos/460537/pexels-photo-460537.jpeg?cs=srgb&dl=pexels-pixabay-460537.jpg&fm=jpg',
        cuisine: 'Steakhouse',
        openingHours: '5:00 PM - 11:00 PM',
        description: 'Juicy and tender steaks grilled to perfection.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
    {
        id: 7,
        name: 'Mediterranean Delights',
        rating: 2,
        distance: '2.8 km',
        imageUri: 'https://images.pexels.com/photos/376464/pexels-photo-376464.jpeg?cs=srgb&dl=pexels-pixabay-376464.jpg&fm=jpg',
        cuisine: 'Mediterranean',
        openingHours: '11:00 AM - 9:30 PM',
        description: 'Mediterranean flavors with a variety of dishes inspired by the region.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
    {
        id: 8,
        name: 'Vegetarian Bliss',
        rating: 4,
        distance: '4.5 km',
        imageUri: 'https://images.pexels.com/photos/449775/pexels-photo-449775.jpeg?cs=srgb&dl=pexels-pixabay-449775.jpg&fm=jpg',
        cuisine: 'Vegetarian',
        openingHours: '9:00 AM - 8:00 PM',
        description: 'Healthy and flavorful vegetarian options for all plant-based enthusiasts.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
    {
        id: 9,
        name: 'Seafood Paradise',
        rating: 5,
        distance: '1 km',
        imageUri: 'https://images.pexels.com/photos/265723/pexels-photo-265723.jpeg?cs=srgb&dl=pexels-pixabay-265723.jpg&fm=jpg',
        cuisine: 'Seafood',
        openingHours: '12:00 PM - 10:00 PM',
        description: 'Fresh and delectable seafood dishes for seafood lovers.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
    {
        id: 10,
        name: 'Indian Spice House',
        rating: 4,
        distance: '6 km',
        imageUri: 'https://images.pexels.com/photos/1640771/pexels-photo-1640771.jpeg?cs=srgb&dl=pexels-sarang-1640771.jpg&fm=jpg',
        cuisine: 'Indian',
        openingHours: '10:30 AM - 9:30 PM',
        description: 'Rich and aromatic Indian dishes with a variety of spices.',
        menuData: {
            Italian: [
                { id: 1, name: 'Spaghetti Bolognese', price: '800.00' },
                { id: 2, name: 'Margherita Pizza', price: '600.00' },
                { id: 3, name: 'Fettuccine Alfredo', price: '700.00' },
            ],
            Japanese: [
                { id: 4, name: 'Sushi Platter', price: '1200.00' },
                { id: 5, name: 'Tempura Roll', price: '900.00' },
                { id: 6, name: 'Miso Soup', price: '400.00' },
            ],
            American: [
                { id: 7, name: 'Classic Cheeseburger', price: '500.00' },
                { id: 8, name: 'BBQ Bacon Burger', price: '600.00' },
                { id: 9, name: 'Crispy Chicken Sandwich', price: '550.00' },
            ],
        },
    },
];